CREATE SEQUENCE producao_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE producao (
	id BIGINT GENERATED BY DEFAULT AS SEQUENCE producao_id_seq PRIMARY KEY,
	titulo VARCHAR(50) NOT NULL,
	ano INT NOT NULL,
	classificacao VARCHAR(20) NOT NULL,
	id_genero BIGINT NOT NULL,
	id_tipo BIGINT NOT NULL,	
	FOREIGN KEY (id_genero) REFERENCES genero(id),
	FOREIGN KEY (id_tipo) REFERENCES tipo_producao(id)
);